/**
 * demo.ts  (npm run demo:mcp)
 *
 * A SELF-CONTAINED, no-external-services demonstration of the Wireframe MCP server. It drives the
 * EXACT engine the MCP tools wrap (engine.ts), so what you see here is what an agent gets when it
 * calls wireframe_step / wireframe_record_done / wireframe_compile / wireframe_run.
 *
 * The corpus is NOT hand-tuned: each session is generated by driving the in-process ops terminal
 * REACTIVELY — random item/field counts, and OUT_OF_STOCK / FIX_REQUIRED recoveries handled as they
 * occur at the black box's OWN seeded rates. This is what a real agent's successful runs look like,
 * and the inference folds the loops + recovery branches into one clean driver from ~a dozen of them.
 *
 * Story:
 *   (a) RECORD a dozen natural successful sessions, via engine.step / engine.recordDone — the same
 *       calls wireframe_step / wireframe_record_done make.
 *   (b) COMPILE — engine.compileProtocol — infer + compile + coverage/safety gate.
 *   (c) RUN the learned workflow toward the goal — engine.run — with ZERO model calls.
 *   (d) ESCALATE — ask the driver for an UNSEEN goal so it safely refuses (no guessing).
 *
 * Run: npm run demo:mcp   (after npm run build)
 */

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { Engine } from "./engine.js";

const PROTOCOL = "ops-order";
const TARGET = "ops";
const SESSION_COUNT = 14;
const FIELD_NAMES = ["ship_name", "ship_addr", "ship_city", "ship_zip", "bill_ref", "priority"];

/** Small seeded PRNG so the demo is reproducible while still drawing varied, natural sessions. */
function mulberry32(a: number): () => number {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hr(): void {
  console.log("─".repeat(74));
}

/**
 * Drive ONE natural successful session against the ops terminal THROUGH Wireframe (engine.step ==
 * wireframe_step), REACTING to whatever the black box returns: substitute on OUT_OF_STOCK, correct
 * on FIX_REQUIRED, as they occur at the target's own seeded rates. Random item/field counts and
 * occasional catalog browsing make this a realistic corpus, not a hand-tuned script.
 */
function recordSession(engine: Engine, seed: number, rng: () => number): { items: number; fields: number; recoveries: string[] } {
  const opt = { responseNamespace: "auto" as const, targetOptions: { seed } };
  const send = (cmd: string): string => engine.step(PROTOCOL, TARGET, cmd, opt).response;
  const nItems = 1 + Math.floor(rng() * 5);
  const nFields = 1 + Math.floor(rng() * 3);
  const recoveries: string[] = [];

  send("LOGIN");
  if (rng() < 0.4) send("LIST_CATALOG");
  send("START_ORDER");
  let added = 0;
  let idx = 0;
  let guard = 0;
  while (added < nItems && guard++ < 40) {
    const sku = `SKU-${1000 + (idx % 24)}`;
    const r = send(`ADD_ITEM sku=${sku}`);
    if (/ERR OUT_OF_STOCK/.test(r)) {
      recoveries.push("OUT_OF_STOCK");
      send(`SUBSTITUTE sku=${sku}`);
      if (/ OK /.test(send(`ADD_ITEM sku=${sku}`))) added++;
    } else if (/ OK /.test(r)) {
      added++;
    }
    idx++;
  }
  for (let f = 0; f < nFields; f++) send(`SET_FIELD ${FIELD_NAMES[f % FIELD_NAMES.length]}=value-${f}`);
  if (/ERR FIX_REQUIRED/.test(send("REVIEW"))) {
    recoveries.push("FIX_REQUIRED");
    send("CORRECT");
    send("REVIEW");
  }
  send("VALIDATE");
  send("SUBMIT");
  send("FINALIZE");
  engine.recordDone(PROTOCOL, "success");
  return { items: nItems, fields: nFields, recoveries };
}

function main(): void {
  const root = mkdtempSync(join(tmpdir(), "wframe-demo-"));
  const engine = new Engine(root);
  const rng = mulberry32(20260624);

  console.log("Wireframe MCP demo — in-process ops terminal, no external services.");
  console.log(`state dir: ${engine.dir}`);
  hr();

  /* (a) RECORD — exactly what wireframe_step + wireframe_record_done do. */
  console.log(`STEP 1  Record ${SESSION_COUNT} NATURAL successful sessions THROUGH Wireframe (== wireframe_step / _record_done)`);
  console.log("        Varied item/field counts; recoveries fire at the black box's own rates — no hand-tuning.");
  for (let i = 0; i < SESSION_COUNT; i++) {
    const s = recordSession(engine, Math.floor(rng() * 1e9), rng);
    console.log(
      `  session ${String(i + 1).padStart(2)} — ${s.items} item(s), ${s.fields} field(s)` +
        (s.recoveries.length ? `, recovered: ${s.recoveries.join("+")}` : "")
    );
  }
  hr();

  /* (b) COMPILE — exactly what wireframe_compile does. */
  console.log("STEP 2  Compile: infer FSM + gate on coverage and forward-ambiguity (== wireframe_compile)");
  const c = engine.compileProtocol(PROTOCOL, { coverageGate: 0.95 });
  console.log(`  states=${c.states} transitions=${c.transitions} terminal=[${c.terminalStates.join(", ")}]`);
  console.log(
    `  coverage=${c.coverage} unsafeContinuationRate=${c.unsafeContinuationRate} ` +
      `requiresFinerAbstraction=${c.requiresFinerAbstraction}`
  );
  console.log(`  responseNamespace=${c.responseNamespace}  GATE PASSED=${c.passed}`);
  if (!c.passed) {
    console.log("  gate did NOT pass — the driver would not be trusted on the learned path. Aborting.");
    process.exit(1);
  }
  hr();

  /* (c) RUN — exactly what wireframe_run does. ZERO model calls on the learned path. */
  console.log("STEP 3  Run the learned workflow deterministically toward the goal (== wireframe_run)");
  console.log('  goal="submitted", task=3 items / 2 fields, with BOTH seeded recovery branches firing');
  const run = engine.run(PROTOCOL, "submitted", {
    task: { items: 3, fields: 2 },
    targetOptions: { seed: 99, forceOutOfStock: true, forceNeedsFix: true },
  });
  for (const [i, step] of run.commands.entries()) {
    console.log(`   ${String(i + 1).padStart(2, "0")}  ${step.command.padEnd(26)} -> ${step.symbol}`);
  }
  console.log(
    `  reachedGoalState=${run.reachedGoal} targetGoalReached=${run.targetGoalReached} ` +
      `escalated=${run.escalated} wrongActions=${run.wrongActions}`
  );
  console.log(`  >>> MODEL CALLS USED: ${run.modelCallsUsed}  (deterministic=${run.deterministic})`);
  hr();

  /* (d) ESCALATE — give the driver a goal it never learned; it refuses to guess. */
  console.log("STEP 4  Ask for an UNSEEN goal/state — the driver SAFELY escalates (no guessing)");
  const esc = engine.run(PROTOCOL, "STATE_THAT_DOES_NOT_EXIST", { targetOptions: { seed: 7 } });
  console.log(
    `  escalated=${esc.escalated} reason=${esc.escalation?.reason ?? "-"} ` +
      `(phase=${esc.escalation?.phase ?? "-"})  commandsIssued=${esc.commands.length}`
  );
  console.log(`  >>> The driver handed control back to the model instead of guessing.`);
  hr();

  console.log("Demo complete.");
  console.log(
    "Takeaway: a repeated sub-workflow an agent would drive with ~14 model-decided tool calls became " +
      "ONE deterministic wireframe_run with 0 model calls — learned from a dozen NATURAL sessions, not hand-tuned scripts."
  );
}

main();
